# Generated by Django 5.0.6 on 2024-07-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_reservation_date_alter_reservation_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='description',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='description',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='description',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
